### ISSUE TITLE
 Crashing on android 13 redmi note 11 with null sensor exception.

### ISSUE THREAD

**Issue by Office-Murtaza** [derysudrajat/compass-qibla#5]
java.lang.NullPointerException: sensorManager.getDefault…(Sensor.TYPE_ORIENTATION) must not be null
                 	at io.github.derysudrajat.compassqibla.CompassQibla$Builder.getcurrentLocation(CompassQibla.kt:46)
                 	at io.github.derysudrajat.compassqibla.CompassQibla$Builder.build$lambda-1(CompassQibla.kt:35)
                 	at io.github.derysudrajat.compassqibla.CompassQibla$Builder.$r8$lambda$PoPQAsbjYqS_X48L083a3Pj-81E(Unknown Source:0)
                 	at io.github.derysudrajat.compassqibla.CompassQibla$Builder$$ExternalSyntheticLambda5.onSuccess(Unknown Source:4)
                 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:210)
                 	at android.os.Looper.loop(Looper.java:299)
                 	at android.app.ActivityThread.main(ActivityThread.java:8309)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by aligkts** [comment]
I also faced this issue.
